version: "3.9"
services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - ALLOW_SIGN_UP=${ALLOW_SIGN_UP}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PRODUCTION=${PRODUCTION}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "8080:80"
  postgres:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    image: "redis:6-alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
