version: "3.9"
volumes:
  html:
    driver: local
services:
  proxy:
    build: ./proxy
    depends_on:
      - api
      - ui
    ports:
      - "8080:80"
    volumes:
      - html:/usr/share/nginx/html
  api:
    build: ./api
    depends_on:
      - postgres
      - redis
    environment:
      - ALLOW_SIGN_UP=true
      - DEVELOPMENT=true
      - HIDE_IP=true
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SESSION_SECRET=${SESSION_SECRET}
  ui:
    build: ./ui
    environment:
      - API_TARGET=${API_TARGET}
      - ALLOW_SIGN_UP=${ALLOW_SIGN_UP}
    volumes:
      - html:/src-ui/dist
  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    image: "redis:6"
