version: "3.9"
services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - ALLOW_SIGN_UP=${ALLOW_SIGN_UP}
      - DEVELOPMENT=${DEVELOPMENT}
      - HIDE_IP=${HIDE_IP}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "8080:80"
  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    image: "redis:6"
